## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'newport'  #for instance daqmx
package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_newport' #to modify
description = 'Set of PyMoDAQ plugins for instruments from Newport (Conex, ESP100,...)'

author = 'Sébastien Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pyvisa']
##